# Generated by Django 4.2.3 on 2023-12-05 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_directory_uploadedfile_directory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directory',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
