# Generated by Django 4.2.3 on 2023-12-05 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_directory_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='directory',
            name='user_profile',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='base.customuser'),
            preserve_default=False,
        ),
    ]
