# Generated by Django 4.2.3 on 2023-12-05 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_directory_user_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='directory',
            name='user_profile',
        ),
    ]
