# Generated by Django 4.2.3 on 2023-12-09 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_uploadedfile_encryption_algorithm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='encrypted_file',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='is_encrypted',
            field=models.BooleanField(default=False),
        ),
    ]
