# Generated by Django 4.2.3 on 2023-12-11 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_uploadedfile_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='directory',
            name='parent_directory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='base.directory'),
        ),
        migrations.AddField(
            model_name='directory',
            name='user_profile',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='base.customuser'),
            preserve_default=False,
        ),
    ]
