# Generated by Django 4.2.3 on 2023-12-11 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_directory_parent_directory_directory_user_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='directory',
            name='parent_directory',
        ),
        migrations.RemoveField(
            model_name='directory',
            name='user_profile',
        ),
    ]
