# Generated by Django 4.2.3 on 2023-12-14 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_remove_directory_parent_directory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='encryption_key_file',
            field=models.FileField(blank=True, null=True, upload_to='encryption_keys'),
        ),
    ]
