# Generated by Django 4.2.3 on 2023-12-14 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_alter_uploadedfile_encryption_key_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='encryption_key_file',
            field=models.FileField(blank=True, null=True, upload_to='encryption_keys'),
        ),
    ]
