# Generated by Django 4.2.3 on 2023-12-14 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_alter_uploadedfile_encryption_key_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedfile',
            name='encryption_key_file',
        ),
    ]
